### ISSUE TITLE
Change arrows

### ISSUE THREAD

**Issue by Haroenv** [osoc16/mobylink#101]
Right now they get replaced to emojis on iOS :joy: so we should probably use an icon. @PjGeeroms had a different idea of how they should look

**Comment by PjGeeroms** [comment]
[Font-Awesome](http://fontawesome.io) for the icons might be an option. @Haroenv

**Comment by Haroenv** [comment]
I'd prefer your triangles to a 100kb font for one icon. Better write it in svg
