### ISSUE TITLE
longer about page

### ISSUE THREAD

**Issue by Haroenv** [osoc16/mobylink#148]
Currently the `about` page only leads to the footer, according to @LisaDebontridder it makes more sense to have an `/about` page/folder that would explain in more detail, and also house for example the press release.

**Comment by PjGeeroms** [comment]
@Haroenv What info is supposed to be on there?
Just logo's of the sponsors etc?

**Comment by Haroenv** [comment]
Nope, a serious about page, with stuff like why, what, press release ...

**Comment by PjGeeroms** [comment]
In the same style as the website or can it be more formal ❓ @Haroenv

**Comment by Haroenv** [comment]
IMHO this would be more formal, but I'm not a copywriter.

**Comment by pietercolpaert** [comment]
Is it okay to close this now?

**Comment by Haroenv** [comment]
@PjGeeroms still wanted to write a longer about page at `/about` instead of it going to the footer, but we didn't do that yet.
