### ISSUE TITLE
design a "story"

### ISSUE THREAD

**Issue by Haroenv** [osoc16/mobylink#16]
going from `small owner` to `large parking garage`, would cover all the steps, explaining `RDFa`, `json-ld`, harvesting data, reusing data. 

cc @LisaDebontridder

**Comment by pietercolpaert** [comment]
When will this issue be closed? When a scenario or user story is written in a markdown file and pushed to master?

**Comment by Haroenv** [comment]
Yes, I think if a markdown file or even another format that explains the project and what pages are needed.
