### ISSUE TITLE
Broken CSS at vocab.datex.org/terms/ ?

### ISSUE THREAD

**Issue by np00** [osoc16/mobylink#202]
I am not sure if it was always like this, but I could swear that last time I visited the website, it looked nicer ;)

**Comment by Haroenv** [comment]
looks like a leading slash disappeared

**Comment by Haroenv** [comment]
fixed it by removing the basurl logic in c098cd501a56182cc66892bd6d558e270e5e7147, I think GitHub updated a major version of Jekyll a while ago, which changed the behaviour of this
