### ISSUE TITLE
typos

### ISSUE THREAD

**Issue by Haroenv** [osoc16/mobylink#86]
> would be great

-> `wouldn't it be great`

> a linked format (...)

-> `a linked format,`

**Comment by PjGeeroms** [comment]
Progress:
- [x]  wouldn't be great -> `wouldn't it be great`
- [x] a linked format (...) -> `a linked format`

Can't seem to find the second typo @Haroenv .

**Comment by Haroenv** [comment]
Second one needs a comma

**Comment by PjGeeroms** [comment]
PJ used find, it wasn't very effective. 
Can't seem to find the text `linked format`

**Comment by PjGeeroms** [comment]
Is it perhaps in this section: 
`Linked data is a way to easily structure all the data that’s being published.
When all the data is published in the linked data format a developer can easily gather and combine it!` ?

**Comment by Haroenv** [comment]
https://github.com/osoc16/mobylink/blob/0b95e935108b163521f2fef385b4b3a7ed596745/_includes/section7.html#L7

**Comment by PjGeeroms** [comment]
Changed the text a bit as well. Can be merged if the changes are correct. 

https://github.com/osoc16/mobylink/blob/fix/typos/_includes/section7.html#L7
